#pragma once

#include <SKVMOIP/defines.h>

namespace Win32
{
	enum KeyCode : u8
	{
		KEYCODE_LEFT_MB = 0x01, /*VK_LBUTTON	0x01	Left mouse button */
		KEYCODE_RIGHT_MB = 0x02, /* VK_RBUTTON	0x02	Right mouse button */
		KEYCODE_CONTROL_BREAK = 0x03, /* VK_CANCEL	0x03	Control-break processing */
		KEYCODE_MIDDLE_MB = 0x04, /* VK_MBUTTON	0x04	Middle mouse button */
		KEYCODE_X1_MB = 0x05, /* VK_XBUTTON1	0x05	X1 mouse button */
		KEYCODE_X2_MB = 0x06, /* VK_XBUTTON2	0x06	X2 mouse button */
		KEYCODE_RESERVED0 = 0x07, /* 0x07	Reserved */
		KEYCODE_BACKSPACE = 0x08, /* VK_BACK	0x08	BACKSPACE key */
		KEYCODE_TAB = 0x09, /* VK_TAB	0x09	TAB key */
		KEYCODE_RESERVED1 = 0x0A, /* 0x0A-0B	Reserved */
		KEYCODE_RESERVED2 = 0x0B,
		KEYCODE_CLEAR = 0x0C, /* VK_CLEAR	0x0C	CLEAR key */
		KEYCODE_RETURN_ENTER = 0x0D, /* VK_RETURN	0x0D	ENTER key */
		KEYCODE_UNASSIGNED0 = 0x0E, /* 0x0E-0F	Unassigned */
		KEYCODE_UNASSIGNED1 = 0x0F,
		KEYCODE_SHIFT = 0x10, /* VK_SHIFT	0x10	SHIFT key */
		KEYCODE_CTRL = 0x11, /* VK_CONTROL	0x11	CTRL key */
		KEYCODE_ALT = 0x12, /* VK_MENU	0x12	ALT key */
		KEYCODE_PAUSE = 0x13, /* VK_PAUSE	0x13	PAUSE key */
		KEYCODE_CAPSLOCK = 0x14, /* VK_CAPITAL	0x14	CAPS LOCK key */
		KEYCODE_KANA = 0x15, /* VK_KANA	0x15	IME Kana mode */
		KEYCODE_HANGUL = 0x15, /* VK_HANGUL	0x15	IME Hangul mode */
		KEYCODE_IME_ON = 0x16, /* VK_IME_ON	0x16	IME On */
		KEYCODE_JUNJA = 0x17, /* VK_JUNJA	0x17	IME Junja mode */
		KEYCODE_FINAL = 0x18, /* VK_FINAL	0x18	IME final mode */
		KEYCODE_HANJA = 0x19, /* VK_HANJA	0x19	IME Hanja mode */
		KEYCODE_KANJI = 0x19, /* VK_KANJI	0x19	IME Kanji mode */
		KEYCODE_IME_OFF = 0x1A, /* VK_IME_OFF	0x1A	IME Off */
		KEYCODE_ESCAPE = 0x1B, /* VK_ESCAPE	0x1B	ESC key */
		KEYCODE_CONVERT = 0x1C, /* VK_CONVERT	0x1C	IME convert */
		KEYCODE_NONCONVERT = 0x1D, /* VK_NONCONVERT	0x1D	IME nonconvert */
		KEYCODE_ACCEPT = 0x1E, /* VK_ACCEPT	0x1E	IME accept */
		KEYCODE_MODE_CHANGE = 0x1F, /* VK_MODECHANGE	0x1F	IME mode change request */
		KEYCODE_SPACEBAR = 0x20, /* VK_SPACE	0x20	SPACEBAR */
		KEYCODE_PAGE_UP = 0x21, /* VK_PRIOR	0x21	PAGE UP key */
		KEYCODE_PAGE_DOWN = 0x22, /* VK_NEXT	0x22	PAGE DOWN key */
		KEYCODE_END = 0x23, /* VK_END	0x23	END key */
		KEYCODE_HOME = 0x24, /* VK_HOME	0x24	HOME key */
		KEYCODE_LEFT_ARROW = 0x25, /* VK_LEFT	0x25	LEFT ARROW key */
		KEYCODE_UP_ARROW = 0x26, /* VK_UP	0x26	UP ARROW key */
		KEYCODE_RIGHT_ARROW = 0x27, /* VK_RIGHT	0x27	RIGHT ARROW key */
		KEYCODE_DOWN_ARROW = 0x28, /* VK_DOWN	0x28	DOWN ARROW key */
		KEYCODE_SELECT = 0x29, /* VK_SELECT	0x29	SELECT key */
		KEYCODE_PRINT = 0x2A, /* VK_PRINT	0x2A	PRINT key */
		KEYCODE_EXECUTE = 0x2B, /* VK_EXECUTE	0x2B	EXECUTE key */
		KEYCODE_PRINT_SCREEN = 0x2C, /* VK_SNAPSHOT	0x2C	PRINT SCREEN key */
		KEYCODE_INSERT = 0x2D, /* VK_INSERT	0x2D	INS key */
		KEYCODE_DELETE = 0x2E, /* VK_DELETE	0x2E	DEL key */
		KEYCODE_HELP = 0x2F, /* VK_HELP	0x2F	HELP key */
		KEYCODE_0 = 0x30, /* 0x30	0 key */
		KEYCODE_1 = 0x31, /* 0x31	1 key */
		KEYCODE_2 = 0x32, /* 0x32	2 key */
		KEYCODE_3 = 0x33, /* 0x33	3 key */
		KEYCODE_4 = 0x34, /* 0x34	4 key */
		KEYCODE_5 = 0x35, /* 0x35	5 key */
		KEYCODE_6 = 0x36, /* 0x36	6 key */
		KEYCODE_7 = 0x37, /* 0x37	7 key */
		KEYCODE_8 = 0x38, /* 0x38	8 key */
		KEYCODE_9 = 0x39, /* 0x39	9 key */
		KEYCODE_UNDEFINED0 = 0x3A, /*-	0x3A-40	Undefined */
		KEYCODE_UNDEFINED1 = 0x40, 
		KEYCODE_A = 0x41, /* 0x41	A key */
		KEYCODE_B = 0x42, /* 0x42	B key */
		KEYCODE_C = 0x43, /* 0x43	C key */
		KEYCODE_D = 0x44, /* 0x44	D key */
		KEYCODE_E = 0x45, /* 0x45	E key */
		KEYCODE_F = 0x46, /* 0x46	F key */
		KEYCODE_G = 0x47, /* 0x47	G key */
		KEYCODE_H = 0x48, /* 0x48	H key */
		KEYCODE_I = 0x49, /* 0x49	I key */
		KEYCODE_J = 0x4A, /* 0x4A	J key */
		KEYCODE_K = 0x4B, /* 0x4B	K key */
		KEYCODE_L = 0x4C, /* 0x4C	L key */
		KEYCODE_M = 0x4D, /* 0x4D	M key */
		KEYCODE_N = 0x4E, /* 0x4E	N key */
		KEYCODE_O = 0x4F, /* 0x4F	O key */
		KEYCODE_P = 0x50, /* 0x50	P key */
		KEYCODE_Q = 0x51, /* 0x51	Q key */
		KEYCODE_R = 0x52, /* 0x52	R key */
		KEYCODE_S = 0x53, /* 0x53	S key */
		KEYCODE_T = 0x54, /* 0x54	T key */
		KEYCODE_U = 0x55, /* 0x55	U key */
		KEYCODE_V = 0x56, /* 0x56	V key */
		KEYCODE_W = 0x57, /* 0x57	W key */
		KEYCODE_X = 0x58, /* 0x58	X key */
		KEYCODE_Y = 0x59, /* 0x59	Y key */
		KEYCODE_Z = 0x5A, /* 0x5A	Z key */
		KEYCODE_LEFT_WINDOWS = 0x5B, /* VK_LWIN	0x5B	Left Windows key */
		KEYCODE_RIGHT_WINDOWS = 0x5C, /* VK_RWIN	0x5C	Right Windows key */
		KEYCODE_APPLICATION = 0x5D, /* VK_APPS	0x5D	Applications key */
		KEYCODE_RESERVED3 = 0x5E, /*-	0x5E	Reserved */
		KEYCODE_SLEEP = 0x5F, /* VK_SLEEP	0x5F	Computer Sleep key */
		KEYCODE_NUMPAD_0 = 0x60, /* VK_NUMPAD0	0x60	Numeric keypad 0 key */
		KEYCODE_NUMPAD_1 = 0x61, /* VK_NUMPAD1	0x61	Numeric keypad 1 key */
		KEYCODE_NUMPAD_2 = 0x62, /* VK_NUMPAD2	0x62	Numeric keypad 2 key */
		KEYCODE_NUMPAD_3 = 0x63, /* VK_NUMPAD3	0x63	Numeric keypad 3 key */
		KEYCODE_NUMPAD_4 = 0x64, /* VK_NUMPAD4	0x64	Numeric keypad 4 key */
		KEYCODE_NUMPAD_5 = 0x65, /* VK_NUMPAD5	0x65	Numeric keypad 5 key */
		KEYCODE_NUMPAD_6 = 0x66, /* VK_NUMPAD6	0x66	Numeric keypad 6 key */
		KEYCODE_NUMPAD_7 = 0x67, /* VK_NUMPAD7	0x67	Numeric keypad 7 key */
		KEYCODE_NUMPAD_8 = 0x68, /* VK_NUMPAD8	0x68	Numeric keypad 8 key */
		KEYCODE_NUMPAD_9 = 0x69, /* VK_NUMPAD9	0x69	Numeric keypad 9 key */
		KEYCODE_MULTIPLY = 0x6A, /* VK_MULTIPLY	0x6A	Multiply key */
		KEYCODE_ADD = 0x6B, /* VK_ADD	0x6B	Add key */
		KEYCODE_SEPARATOR = 0x6C, /* VK_SEPARATOR	0x6C	Separator key */
		KEYCODE_SUBTRACT = 0x6D, /* VK_SUBTRACT	0x6D	Subtract key */
		KEYCODE_DECIMAL = 0x6E, /* VK_DECIMAL	0x6E	Decimal key */
		KEYCODE_DIVIDE = 0x6F, /* VK_DIVIDE	0x6F	Divide key */
		KEYCODE_F1 = 0x70, /* VK_F1	0x70	F1 key */
		KEYCODE_F2 = 0x71, /* VK_F2	0x71	F2 key */
		KEYCODE_F3 = 0x72, /* VK_F3	0x72	F3 key */
		KEYCODE_F4 = 0x73, /* VK_F4	0x73	F4 key */
		KEYCODE_F5 = 0x74, /* VK_F5	0x74	F5 key */
		KEYCODE_F6 = 0x75, /* VK_F6	0x75	F6 key */
		KEYCODE_F7 = 0x76, /* VK_F7	0x76	F7 key */
		KEYCODE_F8 = 0x77, /* VK_F8	0x77	F8 key */
		KEYCODE_F9 = 0x78, /* VK_F9	0x78	F9 key */
		KEYCODE_F10 = 0x79, /* VK_F10	0x79	F10 key */
		KEYCODE_F11 = 0x7A, /* VK_F11	0x7A	F11 key */
		KEYCODE_F12 = 0x7B, /* VK_F12	0x7B	F12 key */
		KEYCODE_F13 = 0x7C, /* VK_F13	0x7C	F13 key */
		KEYCODE_F14 = 0x7D, /* VK_F14	0x7D	F14 key */
		KEYCODE_F15 = 0x7E, /* VK_F15	0x7E	F15 key */
		KEYCODE_F16 = 0x7F, /* VK_F16	0x7F	F16 key */
		KEYCODE_F17 = 0x80, /* VK_F17	0x80	F17 key */
		KEYCODE_F18 = 0x81, /* VK_F18	0x81	F18 key */
		KEYCODE_F19 = 0x82, /* VK_F19	0x82	F19 key */
		KEYCODE_F20 = 0x83, /* VK_F20	0x83	F20 key */
		KEYCODE_F21 = 0x84, /* VK_F21	0x84	F21 key */
		KEYCODE_F22 = 0x85, /* VK_F22	0x85	F22 key */
		KEYCODE_F23 = 0x86, /* VK_F23	0x86	F23 key */
		KEYCODE_F24 = 0x87, /* VK_F24	0x87	F24 key */
		KEYCODE_RESERVED4 = 0x88, /*-	0x88-8F	Reserved */
		KEYCODE_RESERVED5 = 0x89,
		KEYCODE_RESERVED6 = 0x8A,
		KEYCODE_RESERVED7 = 0x8B,
		KEYCODE_RESERVED8 = 0x8C,
		KEYCODE_RESERVED9 = 0x8D,
		KEYCODE_RESERVED10 = 0x8E,
		KEYCODE_RESERVED11 = 0x8F,
		KEYCODE_NUMLOCK = 0x90, /* VK_NUMLOCK	0x90	NUM LOCK key */
		KEYCODE_SCROLLLOCK = 0x91, /* VK_SCROLL	0x91	SCROLL LOCK key */
		KEYCODE_OEM_SPECIFIC0 = 0x92, /*-	0x92-96	OEM specific */
		KEYCODE_OEM_SPECIFIC1 = 0x93,
		KEYCODE_OEM_SPECIFIC2 = 0x94,
		KEYCODE_OEM_SPECIFIC3 = 0x95,
		KEYCODE_OEM_SPECIFIC4 = 0x96,
		KEYCODE_UNASSIGNED2 = 0x97, /* -	0x97-9F	Unassigned */
		KEYCODE_UNASSIGNED3 = 0x98,
		KEYCODE_UNASSIGNED4 = 0x99,
		KEYCODE_UNASSIGNED5 = 0x9A,
		KEYCODE_UNASSIGNED6 = 0x9B,
		KEYCODE_UNASSIGNED7 = 0x9C,
		KEYCODE_UNASSIGNED8 = 0x9D,
		KEYCODE_UNASSIGNED9 = 0x9E,
		KEYCODE_UNASSIGNED10 = 0x9F,
		KEYCODE_LEFT_SHIFT = 0xA0, /* VK_LSHIFT	0xA0	Left SHIFT key */
		KEYCODE_RIGHT_SHIFT = 0xA1, /* VK_RSHIFT	0xA1	Right SHIFT key */
		KEYCODE_LEFT_CTRL = 0xA2, /* VK_LCONTROL	0xA2	Left CONTROL key */
		KEYCODE_RIGHT_CTRL = 0xA3, /* VK_RCONTROL	0xA3	Right CONTROL key */
		KEYCODE_LEFT_ALT = 0xA4, /* VK_LMENU	0xA4	Left ALT key */
		KEYCODE_RIGHT_ALT = 0xA5, /* VK_RMENU	0xA5	Right ALT key */
		KEYCODE_BROWSER_BACK = 0xA6, /* VK_BROWSER_BACK	0xA6	Browser Back key */
		KEYCODE_BROWSER_FORWARD = 0xA7, /* VK_BROWSER_FORWARD	0xA7	Browser Forward key */
		KEYCODE_BROWSER_REFRESH = 0xA8, /* VK_BROWSER_REFRESH	0xA8	Browser Refresh key */
		KEYCODE_BROWSER_STOP = 0xA9, /* VK_BROWSER_STOP	0xA9	Browser Stop key */
		KEYCODE_BROWSER_SEARCH = 0xAA, /* VK_BROWSER_SEARCH	0xAA	Browser Search key */
		KEYCODE_BROWSER_FAVORITES = 0xAB, /* VK_BROWSER_FAVORITES	0xAB	Browser Favorites key */
		KEYCODE_BROWSER_HOME = 0xAC, /* VK_BROWSER_HOME	0xAC	Browser Start and Home key */
		KEYCODE_VOLUME_MUTE = 0xAD, /* VK_VOLUME_MUTE	0xAD	Volume Mute key */
		KEYCODE_VOLUME_DOWN = 0xAE, /* VK_VOLUME_DOWN	0xAE	Volume Down key */
		KEYCODE_VOLUME_UP = 0xAF, /* VK_VOLUME_UP	0xAF	Volume Up key */
		KEYCODE_MEDIA_NEXT_TRACK = 0xB0, /* VK_MEDIA_NEXT_TRACK	0xB0	Next Track key */
		KEYCODE_MEDIA_PREV_TRACK = 0xB1, /* VK_MEDIA_PREV_TRACK	0xB1	Previous Track key */
		KEYCODE_MEDIA_STOP = 0xB2, /* VK_MEDIA_STOP	0xB2	Stop Media key */
		KEYCODE_MEDIA_PLAY_PAUSE = 0xB3, /* VK_MEDIA_PLAY_PAUSE	0xB3	Play/Pause Media key */
		KEYCODE_LAUNCH_MAIL = 0xB4, /* VK_LAUNCH_MAIL	0xB4	Start Mail key */
		KEYCODE_LAUNCH_MEDIA_SELECT = 0xB5, /* VK_LAUNCH_MEDIA_SELECT	0xB5	Select Media key */
		KEYCODE_LAUNCH_APP1 = 0xB6, /* VK_LAUNCH_APP1	0xB6	Start Application 1 key */
		KEYCODE_LAUNCH_APP2 = 0xB7, /* VK_LAUNCH_APP2	0xB7	Start Application 2 key */
		KEYCODE_RESERVED12 = 0xB8, /*-	0xB8-B9	Reserved */
		KEYCODE_RESERVED13 = 0xB9,
		KEYCODE_SEMICOLON_COLON = 0xBA, /* VK_OEM_1	0xBA	Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the ;: key */
		KEYCODE_PLUS = 0xBB, /* VK_OEM_PLUS	0xBB	For any country/region, the + key */
		KEYCODE_COMMA = 0xBC, /* VK_OEM_COMMA	0xBC	For any country/region, the , key */
		KEYCODE_MINUS = 0xBD, /* VK_OEM_MINUS	0xBD	For any country/region, the - key */
		KEYCODE_FULLSTOP = 0xBE, /* VK_OEM_PERIOD	0xBE	For any country/region, the . key */
		KEYCODE_FORWARD_SLASH_QUESTION = 0xBF, /* VK_OEM_2	0xBF	Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the /? key */
		KEYCODE_TILDE = 0xC0, /* VK_OEM_3	0xC0	Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the `~ key */
		KEYCODE_RESERVED14 = 0xC1, /*  -	0xC1-DA	Reserved */
		KEYCODE_RESERVED15 = 0xC2,
		KEYCODE_RESERVED16 = 0xC3,
		KEYCODE_RESERVED17 = 0xC4,
		KEYCODE_RESERVED18 = 0xC5,
		KEYCODE_RESERVED19 = 0xC6,
		KEYCODE_RESERVED20 = 0xC7,
		KEYCODE_RESERVED21 = 0xC8,
		KEYCODE_RESERVED22 = 0xC9,
		KEYCODE_RESERVED23 = 0xCA,
		KEYCODE_RESERVED24 = 0xCB,
		KEYCODE_RESERVED25 = 0xCC,
		KEYCODE_RESERVED26 = 0xCD,
		KEYCODE_RESERVED27 = 0xCE,
		KEYCODE_RESERVED28 = 0xCF,
		KEYCODE_RESERVED29 = 0xD0,
		KEYCODE_RESERVED30 = 0xD1,
		KEYCODE_RESERVED31 = 0xD2,
		KEYCODE_RESERVED32 = 0xD3,
		KEYCODE_RESERVED33 = 0xD4,
		KEYCODE_RESERVED34 = 0xD5,
		KEYCODE_RESERVED35 = 0xD6,
		KEYCODE_RESERVED36 = 0xD7,
		KEYCODE_RESERVED37 = 0xD8,
		KEYCODE_RESERVED38 = 0xD9,
		KEYCODE_RESERVED39 = 0xDA,
		KEYCODE_OPEN_BRACKET_BRACE = 0xDB, /*  VK_OEM_4	0xDB	Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the [{ key */
		KEYCODE_BACKSLASH_PILLOR = 0xDC, /*  VK_OEM_5	0xDC	Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the \\| key */
		KEYCODE_CLOSE_BRACKET_BRACE = 0xDD, /*  VK_OEM_6	0xDD	Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the ]} key */
		KEYCODE_QUOTE_SINGLE_DOUBLE = 0xDE, /*  VK_OEM_7	0xDE	Used for miscellaneous characters; it can vary by keyboard. For the US standard keyboard, the '" key */
		KEYCODE_OEM_8 = 0xDF, /*  VK_OEM_8	0xDF	Used for miscellaneous characters; it can vary by keyboard. */
		KEYCODE_RESERVED40 = 0xE0, /* 0xE0	Reserved */
		KEYCODE_RESERVED41 = 0xE1, /* -	0xE1	OEM specific */
		KEYCODE_LESS_THAN_GREATER_THAN = 0xE2, /* VK_OEM_102	0xE2	The <> keys on the US standard keyboard, or the \\| key on the non-US 102-key keyboard */
		KEYCODE_OEM_SPECIFIC5 = 0xE3, /* -	0xE3-E4	OEM specific */
		KEYCODE_OEM_SPECIFIC6 = 0xE4,
		KEYCODE_PROCESS = 0xE5, /* VK_PROCESSKEY	0xE5	IME PROCESS key */
		KEYCODE_OEM_SPECIFIC7 = 0xE6, /* 0xE6	OEM specific */
		KEYCODE_PACKET = 0xE7, /* VK_PACKET	0xE7	Used to pass Unicode characters as if they were keystrokes. The VK_PACKET key is the low word of a 32-bit Virtual Key value used for non-keyboard input methods. For more information, see Remark in KEYBDINPUT, SendInput, WM_KEYDOWN, and WM_KEYUP */
		KEYCODE_UNASSIGNED11 = 0xE8, /* -	0xE8	Unassigned */
		KEYCODE_OEM_SPECIFIC8 = 0xE9, /* -	0xE9-F5	OEM specific */
		KEYCODE_OEM_SPECIFIC9 = 0xEA,
		KEYCODE_OEM_SPECIFIC10 = 0xEB,
		KEYCODE_OEM_SPECIFIC11 = 0xEC,
		KEYCODE_OEM_SPECIFIC12 = 0xED,
		KEYCODE_OEM_SPECIFIC13 = 0xEE,
		KEYCODE_OEM_SPECIFIC14 = 0xEF,
		KEYCODE_OEM_SPECIFIC15 = 0xF0,
		KEYCODE_OEM_SPECIFIC16 = 0xF1,
		KEYCODE_OEM_SPECIFIC17 = 0xF2,
		KEYCODE_OEM_SPECIFIC18 = 0xF3,
		KEYCODE_OEM_SPECIFIC19 = 0xF4,
		KEYCODE_OEM_SPECIFIC20 = 0xF5,
		KEYCODE_ATTN = 0xF6, /* VK_ATTN	0xF6	Attn key */
		KEYCODE_CRSEL = 0xF7, /* VK_CRSEL	0xF7	CrSel key */
		KEYCODE_EXSEL = 0xF8, /* VK_EXSEL	0xF8	ExSel key */
		KEYCODE_EREOF = 0xF9, /* VK_EREOF	0xF9	Erase EOF key */
		KEYCODE_PLAY = 0xFA, /* VK_PLAY	0xFA	Play key */
		KEYCODE_ZOOM = 0xFB, /* VK_ZOOM	0xFB	Zoom key */
		KEYCODE_NONAME = 0xFC, /* VK_NONAME	0xFC	Reserved */
		KEYCODE_PA1 = 0xFD, /* VK_PA1	0xFD	PA1 key */
		KEYCODE_OEM_CLEAR = 0xFE, /* VK_OEM_CLEAR	0xFE	Clear key */
		KEYCODE_MAX
	};
}
